import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LATENCIES } from '@drift-network/operator';
import type { Analysis } from './analyze.js';
import type { IndexerCheckRow } from './indexer.js';
import { fixed, texEscape, texNumber, weiToEth, type Summary } from './stats.js';

// Every output is a pure function of the analysis: rows are already sorted, numbers have a fixed
// number of digits, and nothing records when it was generated, so the same logs give byte-identical
// files.

const HEADER = '% Generated by drift-e2e analyze. Do not edit; regenerate from the event logs.';

type Cell = string | number | bigint | boolean | undefined;

function csvCell(v: Cell): string {
  if (v === undefined) return '';
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function csv(header: string[], rows: Cell[][]): string {
  return [header, ...rows].map((r) => r.map(csvCell).join(',')).join('\n') + '\n';
}

/** A booktabs tabular; `align` is the column spec (l, r, ...). */
function tex(align: string, header: string[], rows: string[][]): string {
  return [
    HEADER,
    `\\begin{tabular}{${align}}`,
    '\\toprule',
    header.join(' & ') + ' \\\\',
    '\\midrule',
    ...rows.map((r) => r.join(' & ') + ' \\\\'),
    '\\bottomrule',
    '\\end{tabular}',
    ''
  ].join('\n');
}

/** Stable JSON: object keys sorted, bigint as decimal string. */
export function stableJson(v: unknown): string {
  const norm = (x: unknown): unknown => {
    if (typeof x === 'bigint') return x.toString();
    if (Array.isArray(x)) return x.map(norm);
    if (x && typeof x === 'object') {
      return Object.fromEntries(
        Object.keys(x)
          .sort()
          .filter((k) => (x as Record<string, unknown>)[k] !== undefined)
          .map((k) => [k, norm((x as Record<string, unknown>)[k])])
      );
    }
    if (typeof x === 'number' && !Number.isInteger(x)) return Number(x.toFixed(6));
    return x;
  };
  return JSON.stringify(norm(v), null, 2) + '\n';
}

const sec = (v: number | undefined) => (v === undefined ? undefined : fixed(v, 3));
const texSec = (v: number) => texNumber(v, 2);
const summaryCells = (s: Summary): Cell[] => [s.n, sec(s.median), sec(s.p90), sec(s.p99), sec(s.min), sec(s.max)];
const summaryTex = (s: Summary): string[] => [texNumber(s.n), texSec(s.median), texSec(s.p90), texSec(s.p99), texSec(s.min), texSec(s.max)];
const tierName: Record<string, string> = { tier1: 'Tier 1', tier2: 'Tier 2', watcher: 'Watcher', client: 'Client', none: '--' };
const tierTex = (t: string) => tierName[t] ?? texEscape(t);

export function renderFiles(a: Analysis, indexer?: IndexerCheckRow[]): Map<string, string> {
  const files = new Map<string, string>();
  const STATS = ['n', 'median_s', 'p90_s', 'p99_s', 'min_s', 'max_s'];
  const STATS_TEX = ['$n$', 'Median', 'p90', 'p99', 'Min', 'Max'];

  // Data quality.
  files.set('quality.csv', csv(['kind', 'file', 'line', 'detail'], a.issues.map((i) => [i.kind, i.file, i.line, i.detail])));
  const kinds = [...new Set(a.issues.map((i) => i.kind))].sort();
  files.set(
    'quality.tex',
    tex(
      'lr',
      ['Check', 'Count'],
      [
        ['Log files', texNumber(a.inputs.length)],
        ['Lines read', texNumber(a.inputs.reduce((s, f) => s + f.lines, 0))],
        ['Valid events', texNumber(a.inputs.reduce((s, f) => s + f.valid, 0))],
        ['Duplicate observations merged', texNumber(a.counts.duplicates)],
        ...kinds.map((k) => [texEscape(k), texNumber(a.issues.filter((i) => i.kind === k).length)])
      ]
    )
  );
  files.set('inputs.csv', csv(['file', 'lines', 'valid'], a.inputs.map((f) => [f.file, f.lines, f.valid])));

  // Latencies.
  const help = new Map(LATENCIES.map((d) => [d.name, d.help]));
  files.set('latency.csv', csv(['latency', 'tier', 'label', ...STATS], a.latency.map((r) => [r.latency, r.tier, r.label, ...summaryCells(r)])));
  files.set(
    'latency-samples.csv',
    csv(['latency', 'tier', 'label', 'run', 'context', 'epoch', 'key', 'seconds'], a.samples.map((s) => [s.latency, s.tier, s.label, s.run, s.context, s.epoch, s.key, sec(s.seconds)]))
  );
  files.set(
    'latency.tex',
    tex(
      'llrrrrrr',
      ['Latency', 'Tier', ...STATS_TEX],
      a.latency.map((r) => [texEscape(r.label ? `${r.latency} (${r.label})` : r.latency), tierTex(r.tier), ...summaryTex(r)])
    )
  );
  files.set('latency-definitions.csv', csv(['latency', 'definition'], LATENCIES.map((d) => [d.name, help.get(d.name)])));

  // Gas and fees.
  files.set(
    'gas.csv',
    csv(
      ['tier', 'action', 'n_ok', 'gas_median', 'gas_min', 'gas_max', 'fee_median_wei', 'n_reverted', 'reverted_gas', 'fee_total_wei', 'fee_total_eth'],
      a.gas.map((g) => [g.tier, g.action, g.gas.n, g.gas.median, g.gas.min, g.gas.max, g.fee.median, g.reverted, g.revertedGas, g.totalFeeWei, weiToEth(g.totalFeeWei)])
    )
  );
  files.set(
    'gas.tex',
    tex(
      'llrrrrrr',
      ['Tier', 'Action', '$n$', 'Median gas', 'Min', 'Max', 'Reverted', 'Total ETH'],
      a.gas.map((g) => [
        tierTex(g.tier),
        `\\texttt{${texEscape(g.action)}}`,
        texNumber(g.gas.n),
        g.gas.n ? texNumber(g.gas.median) : '--',
        g.gas.n ? texNumber(g.gas.min) : '--',
        g.gas.n ? texNumber(g.gas.max) : '--',
        texNumber(g.reverted),
        weiToEth(g.totalFeeWei)
      ])
    )
  );
  files.set(
    'cost-per-epoch.csv',
    csv(['run', 'context', 'tier', 'epoch', 'txs', 'gas', 'fee_wei', 'fee_eth'], a.epochCosts.map((c) => [c.run, c.context, c.tier, c.epoch, c.txs, c.gas, c.feeWei, weiToEth(c.feeWei)]))
  );
  files.set(
    'cost.tex',
    tex(
      'lrrrrr',
      ['Tier', 'Epochs', 'Total ETH', 'Median ETH / epoch', 'Min', 'Max'],
      a.tierCosts.map((t) => [tierTex(t.tier), texNumber(t.epochs), weiToEth(t.totalFeeWei), weiToEth(t.perEpoch.median), weiToEth(t.perEpoch.min), weiToEth(t.perEpoch.max)])
    )
  );

  // Tier 2.
  files.set(
    'tier2-rounds.csv',
    csv(
      ['run', 'context', 'epoch', 'round', 'proposal_id', 'outcome', 'commits', 'reveals', 'signatures', 'executed'],
      a.rounds.map((r) => [r.run, r.context, r.epoch, r.round, r.proposalId, r.outcome, r.commits, r.reveals, r.signatures, r.executed])
    )
  );
  files.set('tier2-rounds-per-epoch.csv', csv(['run', 'context', 'epoch', 'rounds', 'dead', 'settled'], a.roundsPerEpoch.map((r) => [r.run, r.context, r.epoch, r.rounds, r.dead, r.settled])));
  files.set('tier2-steps.csv', csv(['step', ...STATS], a.tier2Steps.map((s) => [s.step, ...summaryCells(s.summary)])));
  const outcomes = [...new Set(a.rounds.map((r) => r.outcome))].sort();
  const roundHist = [...new Set(a.roundsPerEpoch.map((r) => r.rounds))].sort((x, y) => x - y);
  files.set(
    'tier2.tex',
    tex(
      'lrrrrrr',
      ['Step', ...STATS_TEX],
      [
        ...a.tier2Steps.map((s) => [s.step, ...summaryTex(s.summary)]),
        ...outcomes.map((o) => [`rounds ${texEscape(o)}`, texNumber(a.rounds.filter((r) => r.outcome === o).length), '', '', '', '', '']),
        ...roundHist.map((n) => [`epochs settled in ${n} round${n === 1 ? '' : 's'}`, texNumber(a.roundsPerEpoch.filter((r) => r.rounds === n && r.settled).length), '', '', '', '', ''])
      ]
    )
  );

  // Disputes.
  const d = a.disputes;
  files.set(
    'disputes.csv',
    csv(
      ['tier', 'detected', 'answered', 'unanswerable', 'expired', 'claimed'],
      d.settler.map((s) => [s.tier, s.detected, s.answered, s.unanswerable, s.expired, s.claimed])
    )
  );
  files.set(
    'watcher.csv',
    csv(['roots_seen', 'recomputed', 'divergences', 'omitted_pairs', 'challenges_opened', 'challenges_skipped'], [
      [d.watcher.rootsSeen, d.watcher.recomputed, d.watcher.divergences, d.watcher.omittedPairs, d.watcher.challengesOpened, d.watcher.challengesSkipped]
    ])
  );
  const disputeLatencies = a.latency.filter((r) => ['challenge_detection', 'challenge_response', 'watch_detection', 'watch_recompute'].includes(r.latency) || (r.latency === 'tx_inclusion' && r.label.startsWith('challenge.')));
  files.set(
    'disputes.tex',
    tex(
      'llrrrrrr',
      ['Measure', 'Tier', ...STATS_TEX],
      [
        ...disputeLatencies.map((r) => [texEscape(r.label ? `${r.latency} (${r.label})` : r.latency), tierTex(r.tier), ...summaryTex(r)]),
        ...d.settler.flatMap((s) => [
          ['challenges answered / detected', tierTex(s.tier), `${texNumber(s.answered)} / ${texNumber(s.detected)}`, '', '', '', '', ''],
          ['challenges unanswerable, expired', tierTex(s.tier), `${texNumber(s.unanswerable)}, ${texNumber(s.expired)}`, '', '', '', '', '']
        ]),
        ['divergent roots / roots checked', 'Watcher', `${texNumber(d.watcher.divergences)} / ${texNumber(d.watcher.rootsSeen)}`, '', '', '', '', ''],
        ['watcher challenges opened', 'Watcher', texNumber(d.watcher.challengesOpened), '', '', '', '', '']
      ]
    )
  );

  // Timeline.
  files.set(
    'timeline.csv',
    csv(
      ['run', 'context', 'tier', 'epoch', 't_e', 'o1_wait_s', 'snapshot_s', 'compute_s', 'settle_total_s', 'finalization_s', 'bond_withdrawal_s', 'rounds', 'txs', 'fee_eth'],
      a.timeline.map((t) => [
        t.run, t.context, t.tier, t.epoch, t.tE, sec(t.o1Wait), sec(t.snapshot), sec(t.compute), sec(t.settleTotal), sec(t.finalization), sec(t.bondWithdrawal), t.rounds, t.txs, weiToEth(t.feeWei)
      ])
    )
  );

  // Indexer check.
  if (indexer) {
    files.set(
      'indexer.csv',
      csv(['run', 'context', 'tier', 'epoch', 't_e', 'snapshot_raw_records', 'chain_attestations', 'match'], indexer.map((r) => [r.run, r.context, r.tier, r.epoch, r.tE, r.snapshot, r.chain, r.match]))
    );
    const matched = indexer.filter((r) => r.match).length;
    files.set(
      'indexer.tex',
      tex('lr', ['Indexer check', 'Count'], [
        ['Snapshots checked', texNumber(indexer.length)],
        ['Matching the chain', texNumber(matched)],
        ['Mismatching', texNumber(indexer.length - matched)]
      ])
    );
  }

  files.set(
    'summary.json',
    stableJson({
      method: {
        percentiles: 'nearest-rank: value at rank ceil(p/100 * n) of the ascending sample; median = p50 (lower middle for even n)',
        pairing: 'per key, earliest from-event and earliest to-event across all processes (union of observations)',
        grouping: 'contexts that recorded the same Tier 2 proposalId form one group, labelled by their sorted names',
        units: 'seconds for latencies; gas units; wei and ETH for fees'
      },
      counts: a.counts,
      issues: Object.fromEntries(kinds.map((k) => [k, a.issues.filter((i) => i.kind === k).length])),
      latency: a.latency,
      gas: a.gas,
      tierCosts: a.tierCosts,
      tier2: { steps: a.tier2Steps, rounds: a.rounds.length, outcomes: Object.fromEntries(outcomes.map((o) => [o, a.rounds.filter((r) => r.outcome === o).length])) },
      disputes: a.disputes,
      indexer: indexer && { checked: indexer.length, mismatches: indexer.filter((r) => !r.match).length }
    })
  );
  return files;
}

export function writeFiles(dir: string, files: Map<string, string>): string[] {
  mkdirSync(dir, { recursive: true });
  const names = [...files.keys()].sort();
  for (const name of names) writeFileSync(join(dir, name), files.get(name)!);
  return names;
}
