[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "scripts"
evm_version = "cancun"
fs_permissions = [
  { access = "read-write", path = "./deployments" }
]

[profile.dev]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[profile.ci]
optimizer = true
optimizer_runs = 10_000
via_ir = true
evm_version = "cancun"

[fuzz]
runs = 1000

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
arbitrum-sepolia = "${RPC_ARBITRUM_SEPOLIA}"
avalanche-fuji = "${RPC_AVALANCHE_FUJI}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
